package com.cysion.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cysion.greendao.dao.Attrs;
import com.cysion.greendao.dao.Student;
import com.cysion.greendao.dao.User;

import com.cysion.greendao.dao.AttrsDao;
import com.cysion.greendao.dao.StudentDao;
import com.cysion.greendao.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig attrsDaoConfig;
    private final DaoConfig studentDaoConfig;
    private final DaoConfig userDaoConfig;

    private final AttrsDao attrsDao;
    private final StudentDao studentDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        attrsDaoConfig = daoConfigMap.get(AttrsDao.class).clone();
        attrsDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        attrsDao = new AttrsDao(attrsDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Attrs.class, attrsDao);
        registerDao(Student.class, studentDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        attrsDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public AttrsDao getAttrsDao() {
        return attrsDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
